---
- name: Shutdown EC2 Instance
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Shutdown EC2
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == 'Debian'